export enum technologies {
    TypeScript = "TypeScript",
    JavaScript = "JavaScript",
    HTML = "HTML",
    CSS = "CSS",
    Tailwind = "Tailwind",
    React = "React.js",
    Angular = "Angular",
    CS = "C#",
    CPP = "C++",
    Dotnet = "Dotnet",
    Godot = "Godot",
    Java = "Java",
    Python = "Python",
    Nodejs = "Node.js",
    AWS = "AWS",
    Mongodb = "MongoDB",
    SQL = "SQL",
    Firebase = "Firebase"
}